# Generated by Django 4.1.2 on 2023-07-02 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('deltaT', models.FloatField()),
                ('deltaH', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('molar_mass', models.FloatField()),
                ('deltaT_actual', models.FloatField()),
                ('deltaH_actual', models.FloatField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('id_compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacs.compound')),
            ],
        ),
        migrations.CreateModel(
            name='StartingParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('max', models.FloatField()),
                ('min', models.FloatField()),
                ('id_compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacs.compound')),
            ],
        ),
        migrations.CreateModel(
            name='Relaxation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacs.fit')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.FloatField()),
                ('max', models.FloatField()),
                ('min', models.FloatField()),
                ('error', models.FloatField()),
                ('blocked', models.BooleanField(default=False)),
                ('id_relaxation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacs.relaxation')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T', models.FloatField()),
                ('H', models.FloatField()),
                ('ChiPrime', models.FloatField()),
                ('ChiBis', models.FloatField()),
                ('Freq', models.FloatField()),
                ('hidden', models.BooleanField(default=False)),
                ('id_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacs.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Fit3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=30)),
                ('value', models.FloatField()),
                ('max', models.FloatField()),
                ('min', models.FloatField()),
                ('error', models.FloatField()),
                ('blocked', models.BooleanField(default=False)),
                ('blockedon0', models.BooleanField(default=False)),
                ('id_fit', models.ManyToManyField(to='relacs.fit')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.BinaryField()),
                ('mdate', models.DateField()),
                ('probe_mass', models.FloatField()),
                ('id_compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacs.compound')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CopiedMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T', models.FloatField()),
                ('H', models.FloatField()),
                ('ChiPrime', models.FloatField()),
                ('ChiBis', models.FloatField()),
                ('Freq', models.FloatField()),
                ('hidden', models.BooleanField(default=False)),
                ('id_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacs.fit')),
            ],
        ),
        migrations.AddField(
            model_name='cluster',
            name='id_experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacs.experiment'),
        ),
    ]
