# Generated by Django 4.1.2 on 2022-11-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relacs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='id_team',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
