# Generated by Django 4.1.2 on 2023-07-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='deltaH_actual',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='deltaT_actual',
            field=models.FloatField(null=True),
        ),
    ]
