# Generated by Django 4.1.2 on 2023-07-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacs', '0002_alter_compound_deltah_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='DF',
            field=models.JSONField(default='a'),
            preserve_default=False,
        ),
    ]
